FROM node:20-bullseye-slim AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY server ./server

RUN npm run prisma:generate
RUN npm run build:api

FROM node:20-bullseye-slim
WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/server /app/server
COPY --from=build /app/package.json /app/package.json

EXPOSE 3011
CMD ["node", "server/dist/index.js"]
