# Bygg appen
FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

# Serve med nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
EXPOSE 5174